In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
type(a)

numpy.ndarray

In [5]:
# creatin a 2d array
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
#creating a 3d array
a3 = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[3,4,5,]]])
print(a3)

[[[1 2 3]
  [4 5 6]]

 [[6 7 8]
  [3 4 5]]]


In [ ]:
print(a2.shape)  # gives numbers of rows and coloumn
print(a2.ndim)   # gives dimention of an array
print(a3.ndim)   # datatype of element 
print(a2.dtype)  

(2, 5)
2
3
int64


In [18]:
np.arange(10)
np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [19]:
np.random.randint(1,11, size=(2,3))  # to create array


array([[ 7,  3, 10],
       [10,  7,  3]], dtype=int32)

In [20]:
x = np.array([[7,2,3],
              [7,5,4],
              [4,5,6]])
y = np.array([[1,4,3],
              [2,3,4],
              [4,3,1]])
print(x)
print(y)

[[7 2 3]
 [7 5 4]
 [4 5 6]]
[[1 4 3]
 [2 3 4]
 [4 3 1]]
