In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
type(a)

numpy.ndarray

In [4]:
# creatin a 2d array
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
#creating a 3d array
a3 = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[3,4,5,]]])
print(a3)

[[[1 2 3]
  [4 5 6]]

 [[6 7 8]
  [3 4 5]]]


In [6]:
print(a2.shape)  # gives numbers of rows and coloumn
print(a2.ndim)   # gives dimention of an array
print(a3.ndim)   # datatype of element 
print(a2.dtype)  

(2, 5)
2
3
int64


In [7]:
np.arange(10)
np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
np.random.randint(1,11, size=(2,3))  # to create array


array([[ 5,  4,  1],
       [10,  6,  4]], dtype=int32)

In [9]:
x = np.array([[7,2,3],
              [7,5,4],
              [4,5,6]])
y = np.array([[1,4,3],
              [2,3,4],
              [4,3,1]])
print(x)
print(y)

[[7 2 3]
 [7 5 4]
 [4 5 6]]
[[1 4 3]
 [2 3 4]
 [4 3 1]]


In [ ]:
print(x*y) #matrix multiplication

[[ 7  8  9]
 [14 15 16]
 [16 15  6]]


In [11]:
# matrix multiplication
print(x@y)

[[23 43 32]
 [33 55 45]
 [38 49 38]]


In [12]:
# matrix multiplication
print(x,y)

[[7 2 3]
 [7 5 4]
 [4 5 6]] [[1 4 3]
 [2 3 4]
 [4 3 1]]


In [ ]:
np.dot(x,y) # matrix muktiplication 

array([[23, 43, 32],
       [33, 55, 45],
       [38, 49, 38]])

In [ ]:
x.prod()   # product of all element of the array

np.int64(705600)

In [ ]:
x.mean()   # mean of all elements

np.float64(4.777777777777778)

In [16]:
y.mean()

np.float64(2.7777777777777777)

In [17]:
print(x)

[[7 2 3]
 [7 5 4]
 [4 5 6]]


In [18]:
x.mean(axis = 0)   #coloun wise mean

array([6.        , 4.        , 4.33333333])

In [19]:
y.mean(axis = 1)  #row wise mean

array([2.66666667, 3.        , 2.66666667])

In [ ]:
print(x.sum())
print(x.std())  # std deviation
print(x.var())    #variance

43
1.617802197617893
2.617283950617284


In [23]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25))   # 1st quartile
print(np.percentile(a,50))   # median
print(np.percentile(a,75))   # 3rd quartile


3.0
5.0
7.0


In [27]:
b = np.random.randint(1,11,)  #size of matrix
print(b)

5


In [28]:
b = np.random.randint(11,100, (4,4))
print(b)

[[59 39 54 90]
 [37 16 83 69]
 [56 58 56 33]
 [25 89 48 94]]


In [29]:
print(x[0])  #1st row
print(x[0,1])  #1st row and 2nd coloumn's first element
print(x[-1])

print(x[:3])
print(x[3:])

[7 2 3]
2
[4 5 6]
[[7 2 3]
 [7 5 4]
 [4 5 6]]
[]
